# Generated by Django 2.1.7 on 2020-01-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
